name: Release

on:
  project_card:
    types: edited

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Release new version
        if: ${{ github.event.project_card.id == 40352052}}
        run: |
          node release.js ${{ github.event.project_card.note }}