name: Release

on:
  project_card:
    types: edited

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Release new version
        run: |
          echo ${{ github.event.project_card.id }}
          echo ${{ github.event.project_card.note }}