name: Release

on:
  project_card:
    types: edited

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ItsKarma/aws-cli@v1.70.0
      - name: Release new version
        if: ${{ github.event.project_card.id == 40352052}}
        run: |
          node release.js ${{ github.event.project_card.note }}